### ISSUE TITLE
Show Difference pop up window doesn't seems to run

### ISSUE THREAD

**Issue by killersmey** [VEckardt/IntegrityShowSuspectDetails#1]
Hello Mister VEckardt,

I'm working on Automotive industry and start to configure PTC Windchill tool for a few months now.
I got the information from one of my customer that you develop very good and powerfull tools to enhance greatly our daily job on PTC Windchill!

I'm very exited to test the IntegrityShowSuspectDetails add on!!
I downloaded and install it on current version of WindChill (Version 12.3.1.0)

![About](https://user-images.githubusercontent.com/81330606/112381612-10ae6580-8ceb-11eb-85f4-417797b3dbe3.png)

I selected one specific node and launch the add-on, as you can see on the picture below, the first window pops up with information about the modified information

![image](https://user-images.githubusercontent.com/81330606/112381676-24f26280-8ceb-11eb-9e85-58361000f05e.png)

But when I click on the Show Difference button, nothing happend...

Can you please provide me some basic advices to know what to do ?

Here is the content of the Text box provided above the 2 buttons 👍 

![image](https://user-images.githubusercontent.com/81330606/112382035-9e8a5080-8ceb-11eb-8346-62a2d4a0da6d.png)

UPDATE INFORMATION : This morning I replace javaw.exe by java.exe to be able to launch cmd line and have more details

Here is the output 
`/showsuspect/resources/ShowSuspectRB.properties
mars 25, 2021 9:07:09 AM com.ptc.services.common.api.ApplicationProperties log
INFO: (1) Reading Properties ...
mars 25, 2021 9:07:09 AM com.ptc.services.common.api.ApplicationProperties log
INFO: (2)  Reading from file: C:\Program Files\Windchill\RVSClient12\IntegrityShowSuspect.properties (P1)
mars 25, 2021 9:07:09 AM com.ptc.services.common.api.ApplicationProperties log
INFO: (2)  Property file in default path not found.
mars 25, 2021 9:07:09 AM com.ptc.services.common.api.ApplicationProperties log
INFO: (2)  CLASSPATH not defined, skipping property file search in classpath. (P2)
Command [ im issues --fields=Type,Trace Status -- 339268 ] at svwptcwdc001t:7001[31ms]
Command [ im types --fields=visibleFields -- Requirement ] at svwptcwdc001t:7001[16ms]
Command [ im fields --fields=ID,position,name,type,displayName,description,computation,maxLength,backedBy,default,relevanceRule,pairedField,trace,isForward,allowedTypes -- Summary State Project Attachments Parameter Values Suspect Count Include Reference Priority Satisfied By Validated By Is Related To Include Subsegment in Metrics Validated By Trace Count Trace Status Downstream Trace Count Upstream Trace Count Validated By Pass Count Validated By Pass Percentage Additional Comments Category Int Value Modelled By Hide Decomposed From Is Related To' Mitigates Revision Date Validated By Trace Health Text Input Shared Item Revision Date Text Attachments Project State Parameter Values From Shared Item Parameters From Shared Item External ID Project Phase FVA Implements Name Windchill Item DOORSID Doors Link Functional Allocation Structural Allocation *DEPRECATED* Notes *DEPRECATED* Rationale *DEPRECATED* Reference_Number *DEPRECATED* Reference_Version Detailed By Reference Number Reference Version Notes Rationale Defines Satisfied By Trace Count Detailed By Trace Count Reference Number Exists Validated By (Development Team) Related Tasks ] at svwptcwdc001t:7001[47ms]
Determined UpStream traceNames: Implements,Decomposed From,Is Related To',Mitigates
Command [ im viewissue --showHistory -- 339268 ] at svwptcwdc001t:7001[134ms]
Checking relationship 'Implements' ...
Checking relationship 'Decomposed From' ...
Relationship 'Decomposed From' is currently suspect!
Found traced item 339289 ...
Command [ im issues --AsOf=Mar 24, 2021 6:36:13 PM --fields=Trace Status -- 339268 ] at svwptcwdc001t:7001[39ms]
Item has become suspect on the Wed Mar 24 18:36:14 CET 2021 based on a change in item 339289
Command [ im issues --fields=type -- 339289 ] at svwptcwdc001t:7001[52ms]
Command [ im types --fields=significantEdit -- Customer Input ] at svwptcwdc001t:7001[13ms]
Category,Text,Text Attachments
Fields in stack: 14
Command [ im fields --fields=ID,position,name,type,displayName,description,computation,maxLength,backedBy,default,relevanceRule,pairedField,trace,isForward,allowedTypes -- Category Text Text Attachments ] at svwptcwdc001t:7001[12ms]
Fields in stack: 17
Step 1: Get current item values from 339289 ...
Command [ im issues --fields=Category,Text,Text Attachments,Modified By,Significant Edit Date,References -- 339289 ] at svwptcwdc001t:7001[62ms]
Step 2: Get item values from 339289before significant change  ...
Command [ im issues --AsOf=Mar 24, 2021 6:36:13 PM --fields=Category,Text,Text Attachments -- 339289 ] at svwptcwdc001t:7001[67ms]
Step 3: Get item values from 339289after significant change ...
Command [ im issues --AsOf=Mar 24, 2021 6:36:15 PM --fields=Modified By,Significant Edit Date -- 339289 ] at svwptcwdc001t:7001[46ms]
Checking field 'Category' ...
Category: before=Imported Requirement #|# current=Imported Requirement
Checking field 'Text' ...
Text: before=CustReq6 UPDATE #|# current=CustReq6 UPDATE2
test
Field content for 'Text' has changed!
searchLatestChangeRec: field to check is Text
searchLatestChangeRec: the field is a FVA field
Command [ im viewissue --showHistory -- 1757388 ] at svwptcwdc001t:7001[86ms]
Shared: Field to look for in history is 'Shared Text' ...
Shared: For all 3 Item History Entries ...
Found historical entry with 'Shared Text' = CustReq6 UPDATE2
test
modBy = Maxime Willemyns
modDate = Wed Mar 24 18:36:14 CET 2021
Shared: Text found.
Checking field 'Text Attachments' ...
Text Attachments: before= #|# current=
Checking relationship 'Is Related To'' ...
Checking relationship 'Mitigates' ...
1 suspect change(s) found.
Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1774)
        at javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1657)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
        at javafx.event.Event.fireEvent(Event.java:198)
        at javafx.scene.Node.fireEvent(Node.java:8411)
        at javafx.scene.control.Button.fire(Button.java:185)
        at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:182)
        at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:96)
        at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:89)
        at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
        at javafx.event.Event.fireEvent(Event.java:198)
        at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
        at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
        at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
        at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:394)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:432)
        at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:431)
        at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
        at com.sun.glass.ui.View.notifyMouse(View.java:937)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$3(WinApplication.java:177)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:72)
        at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:276)
        at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1769)
        ... 48 more
Caused by: java.lang.UnsatisfiedLinkError: Can't load library: C:\Program Files\Amazon Corretto\jdk1.8.0_242\jre\bin\jfxwebkit.dll
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1831)
        at java.lang.Runtime.load0(Runtime.java:810)
        at java.lang.System.load(System.java:1088)
        at com.sun.glass.utils.NativeLibLoader.loadLibraryFullPath(NativeLibLoader.java:201)
        at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:94)
        at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:39)
        at com.sun.webkit.WebPage.lambda$static$0(WebPage.java:133)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.webkit.WebPage.<clinit>(WebPage.java:132)
        at javafx.scene.web.WebEngine.<init>(WebEngine.java:881)
        at javafx.scene.web.WebEngine.<init>(WebEngine.java:868)
        at javafx.scene.web.WebView.<init>(WebView.java:273)
        at showsuspect.ShowSuspectController$MyBrowser.<init>(ShowSuspectController.java:101)
        at showsuspect.ShowSuspectController.openBrowser(ShowSuspectController.java:91)
        at showsuspect.ShowSuspectController.handleCurrVsPrevious(ShowSuspectController.java:81)
        ... 58 more
`
It seems at least that jdk1.8.0_242 can not load jfxwebkit.dll

[UPDATE] I checked on the Internet and FX Media library do NOT exist on Amazon Coretto, I need probabley to  use another JDK... I will make a test.

With my best regards,
Julien

**Comment by killersmey** [comment]
Well Finally, I was able to solve the issue. I uninstall Amazon Correto from the client, install normal JRE oracle java plug in and updated manually the *.lax files containing path to Java.exe folder And all works just fine !!

Thank for the job it's a good tool!!

**Comment by killersmey** [comment]
I close the issue
